apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: shpd-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Puedes cambiar este puerto si está en uso