apiVersion: apps/v1
kind: Deployment
metadata:
  name: shpd-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shpd-frontend
  template:
    metadata:
      labels:
        app: shpd-frontend
    spec:
      containers:
        - name: frontend
          image: shpd-frontend:1.7.0
      
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"